import './globals.css'
import { Roboto } from 'next/font/google'
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "./theme/theme";

const inter = Roboto({ subsets: ['latin'], weight: "300" })

export const metadata = {
  title: 'adversea',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
