export type DetailEntityResponse = {
  "query":string,
  "sanctions":{
    "addresses":string,
    "aliases":string,
    "birth_date":string,
    "countries":string,
    "dataset":string,
    "emails":string,
    "id":string,
    "identifiers":number,
    "name":string,
    "name_ascii":string,
    "phones":string,
    "sanctions":string,
    "schema":string
  }
  "pep":{
    "addresses":string,
    "aliases":string,
    "birth_date":string,
    "countries":string,
    "dataset":string,
    "emails":string,
    "id":string,
    "identifiers":string,
    "name":string,
    "name_ascii":string,
    "phones":string,
    "sanctions":string,
    "schema":string
  }
}